export const url = {
  register: 'register',
  verify: 'verifyOtp',
  resendOtp: 'resendOtpCode',
  login: 'login',
  forgotPassword: 'forgotPassword',
  updateForgotPassword: 'updateForgotPassword',
  goalsImages: 'getAllGoalsImages',
  saveGoal: 'saveUserGoal',
  getUserGoals: 'getUserGoals',
  updateUserGoal: 'updateUserGoal',
  getAllBoosts: 'getAllBoosts',
  saveUserBoost: 'saveUserBoost',
  removeUserBoost: 'removeUserBoost',
  getInspirationsTypes: 'getInspirationsTypes',
  getAllInspirations: 'getAllInspirations',
  getNotificationsSettings: 'getNotificationsSettings',
  saveUserNotifications: 'saveUserNotifications',
  signOut: 'SignOut',
  deleteUserData: 'deleteUserData',
};
